version: '3.9'

services:
  frost-mind-postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - frost-mind-postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=frost-mind-db

volumes:
  frost-mind-postgres_data:
