version: '3.9'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nimda
      - POSTGRES_USER=postgres
      - POSTGRES_DB=full_app_template

volumes:
  postgres_data:
