version: '3.9'

services:
  our-freezer-postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - our-freezer-postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=our-freezer-db

volumes:
  our-freezer-postgres_data:
